import "./globals.css"

import type { Metadata } from "next"
import { Instrument_Sans } from "next/font/google"

import { HiOutlineCog } from "react-icons/hi"
import MainNavigation from "./MainNavigation"
import Provider from "./web3/Provider"
import AuthSentinel from "./AuthSentinel"

const mainFont = Instrument_Sans({
  display: "block",
  subsets: [],
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Pago Wallet",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased`}>
        <Provider>
          <AuthSentinel />
          <div className="min-h-screen flex flex-col">
            <nav className="px-3 shrink-0 h-16 mb-12 max-w-6xl mx-auto w-full flex items-center gap-4 justify-between">
              <button className="size-10">
                <HiOutlineCog className="text-3xl" />
              </button>
              <button className="bg-black rounded-full size-9">B</button>
            </nav>
            {children}
            <MainNavigation />
          </div>
        </Provider>
      </body>
    </html>
  )
}
