import "./globals.css"

import type { Metadata } from "next"
import { Instrument_Sans } from "next/font/google"

import { HiOutlineCog } from "react-icons/hi"
import MainNavigation from "./MainNavigation"

const mainFont = Instrument_Sans({
  display: "block",
  subsets: [],
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Pago Wallet",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased`}>
        <div className="h-screen flex flex-col">
          <nav className="px-3 h-16 mb-12 max-w-6xl mx-auto w-full flex items-center gap-4 justify-between">
            <button className="size-10">
              <HiOutlineCog className="text-3xl" />
            </button>
            <button className="bg-black rounded-full size-8">B</button>
          </nav>
          {children}
          <MainNavigation />
        </div>
      </body>
    </html>
  )
}
